<?php get_header(); ?>
<?php scm_component('hub-hero', [
  'eyebrow' => 'SAMUEL &amp; CO MARKETS',
  'title' => 'Your daily markets operating system.',
  'lead' => 'One membership bringing together premium research, live market sessions, structured learning and a serious trader community.',
  'image_class' => 'scm-hub-hero__image--membership',
  'quote' => 'Less noise. Better routine. Deeper understanding.',
  'primary' => ['Join for £99/month', '#plans'],
  'secondary' => ['Compare plans', '#plans'],
]); ?>
<section class="scm-section" id="plans"><div class="scm-shell"><div class="scm-section-head"><div><span class="scm-eyebrow">MEMBERSHIP</span><h2>Choose how you want to use Samuel &amp; Co.</h2></div></div><div class="scm-price-grid"><article class="scm-price-card"><span class="scm-eyebrow">FREE</span><h3>Market Reader</h3><div class="scm-price">£0</div><small>forever</small><ul><li>Morning Brief</li><li>Selected market news</li><li>Free Learn hub</li><li>Weekly public analysis</li></ul><a class="scm-button" href="#">Join free</a></article><article class="scm-price-card scm-price-card--featured"><span class="scm-eyebrow">SAMUEL &amp; CO MARKETS</span><h3>Markets Member</h3><div class="scm-price">£99</div><small>per month, VAT inclusive</small><ul><li>Morning Brief + US Open</li><li>Premium research library</li><li>Weekly live market session</li><li>Weekly market plan &amp; watchlist</li><li>Full lesson and video library</li><li>Private community</li><li>Monthly masterclass</li><li>Member events</li></ul><a class="scm-button scm-button--gold" href="#">Join Samuel &amp; Co Markets</a></article><article class="scm-price-card"><span class="scm-eyebrow">ANNUAL</span><h3>Markets Annual</h3><div class="scm-price">£990</div><small>per year</small><ul><li>Everything in Markets Member</li><li>Two months equivalent saving</li><li>Annual member status</li><li>Priority event access</li></ul><a class="scm-button" href="#">Choose annual</a></article></div></div></section>
<section class="scm-section scm-section--soft"><div class="scm-shell"><div class="scm-section-head"><div><span class="scm-eyebrow">WHAT YOU GET</span><h2>Built around a weekly market routine.</h2></div></div><div class="scm-lesson-grid"><article class="scm-lesson"><span class="scm-meta">DAILY</span><h3>Briefings</h3><p>Morning Brief and US Open keep the day anchored around what matters.</p></article><article class="scm-lesson"><span class="scm-meta">WEEKLY</span><h3>Live Market Session</h3><p>Walk through positioning, market structure and the coming week's key risks.</p></article><article class="scm-lesson"><span class="scm-meta">ONGOING</span><h3>Premium Research</h3><p>Deeper theses, scenarios and frameworks beyond the headlines.</p></article><article class="scm-lesson"><span class="scm-meta">COMMUNITY</span><h3>Serious Traders</h3><p>A private environment for people who want to improve their market process.</p></article></div></div></section>
<?php get_footer(); ?>